# Harmony Jekyll theme general configurations

# Base URL
baseurl: ""

# Site live URL
url: http://jiulidaji.cn

# Localhost
# url: http://127.0.0.1:4000

# Production URL for sitemap
production_url: http://jiulidaji.cn

# Static image folder
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Harmony theme configuration. Please change accordingly.
harmony:
  name: 九里大集
  # Little description about your site
  description: Eternachen's Blog
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
   Eternachen's blog，九里大集。专注于各类计算机技术，记录所感所想所思。
   分享 Linux 使用技巧，Java 开发技术，以及其他程序设计经验。
  basetheme: theme-base-01 # Pre-defined themes are darken, blue-water, reddish.
  author: # Author details
    name: 九里大集
    email: jiulidaji@qq.com
    url: http://jiulidaji.cn

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-174912147-1

  # Profile links, leave blank to ignore
  social:
    github:
    twitter:
    facebook:
    gplus:
    linkedin: https://www.linkedin.com/in/eternachen/
    dribble:
    pinterest:
  social_zh:
    email: jiulidaji@qq.com
    weibo:
    github: eternachen
    qq:
    wechat:
    rss: /feed
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink: /:year/:month/:day/:title

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: compressed

theme: minimal-mistakes-jekyll

# Preserve old Harmony theme settings under legacy_theme in case we need them later
legacy_theme:
  harmony:
    name: 九里大集
    description: Eternachen's Blog
    meta_description: >
      Eternachen's blog，九里大集。专注于各类计算机技术，记录所感所想所思。
    basetheme: theme-base-01
    author:
      name: 九里大集
      email: jiulidaji@qq.com
      url: http://jiulidaji.cn
    google_analytics_key: UA-174912147-1
    social_zh:
      email: jiulidaji@qq.com
      github: eternachen
      rss: /feed

# Minimal Mistakes recommended settings (replace/adjust as needed)
title: "九里大集 | Eternachen's Blog"
email: jiulidaji@qq.com
repository: eternachen/eternachen.github.io
